
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//	   Copyright (c) 2017 Citrix ShareFile. All rights reserved.
// </auto-generated>
// ------------------------------------------------------------------------------

package com.citrix.sharefile.api.models;

import java.util.Map;

import com.google.gson.annotations.SerializedName;

public class SFZoneUsageBreakdown extends SFODataObject {

	@SerializedName("ZonesToUsage")
	private Map<String, SFAccountZoneUsage> ZonesToUsage;

	public Map<String, SFAccountZoneUsage> getZonesToUsage() {
		return this.ZonesToUsage;
	}

	public void setZonesToUsage(Map<String, SFAccountZoneUsage> zonestousage) {
		this.ZonesToUsage = zonestousage;
	}

}