name: Publish package to GitHub Packages
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

          #  - name: Publish artifact
          #    env:
          #       CREDENTIALS: -PGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -PGITHUB_USER=${{ github.actor }}

          #    run: ./gradlew -Pversion=${{github.ref_name}} publish ${CREDENTIALS}
          #  - name: Gradle bygg av services
          #    env:
          #     CREDENTIALS: -PGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -PGITHUB_USER=${{ github.actor }}
          #    run: ./gradlew build ${CREDENTIALS}

      - name: Publish artifact
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
          arguments: publish -PGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -PGITHUB_USER=${{ github.actor }}
